type Month = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12;

type Book = {
  title: string;
  author: string | string[];
  description?: string;
  image: string;
  link?: string;
  category: "literature" | "growth" | "software";
  status?: "read" | "reading" | "pending";
  readAt?: { month?: Month; year: number };
};

const literatureBooks: Book[] = [
  {
    title: "Eva",
    author: "Arturo Pérez-Reverte",
    description: "",
    image: "eva.jpg",
    link: "https://amzn.to/4lbRQ4Y",
    category: "literature",
    status: "pending",
  },
  {
    title: "Chaman",
    author: "Noah Gordon",
    description: "",
    image: "chaman.jpg",
    link: "https://amzn.to/4lGo8VL",
    category: "literature",
    status: "pending",
  },
  // 2025
  {
    title: "El temor de un hombre sabio",
    author: "Patrick Rothfuss",
    description: "",
    image: "el-temor-de-un-hombre-sabio.jpg",
    link: "https://amzn.to/3G8Affb",
    category: "literature",
    readAt: { month: 6, year: 2025 },
  },
  {
    title: "La fortaleza digital",
    author: "Dan Brown",
    description: "",
    image: "la-fortaleza-digital.jpg",
    link: "https://amzn.to/3I80keZ",
    category: "literature",
    readAt: { month: 9, year: 2024 },
  },
  {
    title: "El nombre del viento",
    author: "Patrick Rothfuss",
    description: "",
    image: "el-nombre-del-viento.jpg",
    link: "https://amzn.to/4lDjZlj",
    category: "literature",
    readAt: { month: 6, year: 2024 },
  },
  {
    title: "Blackwater - La riada",
    author: "Michael McDowell",
    description: "",
    image: "blackwater-la-riada.jpg",
    link: "https://amzn.to/4khS7lG",
    category: "literature",
    readAt: { month: 1, year: 2024 },
  },
  {
    title: "La historia secreta del señor White",
    author: "Juan Gómez-Jurado",
    description: "",
    image: "la-historia-secreta-del-senor-white.jpg",
    link: "https://amzn.to/40CrPn5",
    category: "literature",
    readAt: { month: 12, year: 2022 },
  },
  {
    title: "Loba Negra",
    author: "Juan Gómez-Jurado",
    description: "",
    image: "loba-negra.jpg",
    link: "https://amzn.to/44sHKWp",
    category: "literature",
    readAt: { month: 1, year: 2023 },
  },
  {
    title: "Reina Roja",
    author: "Juan Gómez-Jurado",
    description: "",
    image: "reina-roja.jpg",
    link: "https://amzn.to/4lGKPct",
    category: "literature",
    readAt: { month: 10, year: 2022 },
  },
  {
    title: "Cicatriz",
    author: "Juan Gómez-Jurado",
    description: "",
    image: "cicatriz.jpg",
    link: "https://amzn.to/4nqXO3H",
    category: "literature",
    readAt: { month: 9, year: 2022 },
  },
  {
    title: "El paciente",
    author: "Juan Gómez-Jurado",
    description: "",
    image: "el-paciente.jpg",
    link: "https://amzn.to/4ezDyc7",
    category: "literature",
    readAt: { month: 8, year: 2022 },
  },
  {
    title: "Falcó",
    author: "Arturo Pérez-Reverte",
    description: "",
    image: "falco.jpg",
    link: "https://amzn.to/45TbFt5",
    category: "literature",
    readAt: { month: 6, year: 2020 },
  },
  {
    title: "La historia de lisey",
    author: "Stephen King",
    description: "",
    image: "la-historia-de-lisey.jpg",
    link: "https://amzn.to/44KXGED",
    category: "literature",
    readAt: { month: 9, year: 2012 },
  },
  {
    title: "La cúpula",
    author: "Stephen King",
    description: "",
    image: "la-cupula.jpg",
    link: "https://amzn.to/3ZYKtpc",
    category: "literature",
    readAt: { year: 2015 },
  },
  {
    title: "La conspiración",
    author: "Dan Brown",
    description: "",
    image: "la-conspiracion.jpg",
    link: "https://amzn.to/3GwLX38",
    category: "literature",
    readAt: { month: 1, year: 2012 },
  },
  {
    title: "Los pilares de la tierra",
    author: "Ken Follett",
    description: "",
    image: "los-pilares-de-la-tierra.jpg",
    link: "https://amzn.to/4lghpSG",
    category: "literature",
    readAt: { month: 3, year: 2012 },
  },
  // 2010
  {
    title: "Un lugar llamado libertad",
    author: "Ken Follett",
    description: "",
    image: "un-lugar-llamado-libertad.jpg",
    link: "https://amzn.to/3ZYGHft",
    category: "literature",
    readAt: { month: 10, year: 2010 },
  },
  {
    title: "El Hobbit",
    author: "J.R.R. Tolkien",
    description: "",
    image: "el-hobbit.jpg",
    link: "https://amzn.to/3ZYTPkO",
    category: "literature",
    readAt: { month: 1, year: 2007 },
  },
  {
    title: "Blockade Billy",
    author: "Stephen King",
    description: "",
    image: "blockade-billy.jpg",
    link: "https://amzn.to/4lB5iiA",
    category: "literature",
    readAt: { month: 6, year: 2006 },
  },
  {
    title: "It",
    author: "Stephen King",
    description: "",
    image: "it.jpg",
    link: "https://amzn.to/3Ti6knI",
    category: "literature",
    readAt: { month: 5, year: 2005 },
  },
  // 2004
  {
    title: "El médico",
    author: "Noah Gordon",
    description: "",
    image: "el-medico.jpg",
    link: "https://amzn.to/4kqWXx9",
    category: "literature",
    readAt: { month: 6, year: 2004 },
  },
  {
    title: "Cell",
    author: "Stephen King",
    description: "",
    image: "cell.jpg",
    link: "https://amzn.to/3TmBzhy",
    category: "literature",
    readAt: { month: 1, year: 2004 },
  },
  // 2003
  {
    title: "El señor de los anillos (Trilogía)",
    author: "J.R.R. Tolkien",
    description: "",
    image: "el-senor-de-los-anillos-trilogia.jpg",
    link: "https://amzn.to/4knjcEe",
    category: "literature",
    readAt: {
      month: 4,
      year: 2003,
    },
  },
  {
    title: "Corazones en la Atlántida",
    author: "Stephen King",
    description: "",
    image: "corazones-en-la-atlantida.jpg",
    link: "https://www.casadellibro.com/libro-corazones-en-la-atlantida/9788497592956/873686",
    category: "literature",
    readAt: { month: 6, year: 2003 },
  },
  {
    title: "El último trabajo del señor Luna",
    author: "César Mallorquí",
    description: "",
    image: "el-ultimo-trabajo-del-senor-luna.jpg",
    link: "https://amzn.to/3IgJWZy",
    category: "literature",
    readAt: { month: 2, year: 2003 },
  },
];

const growthBooks: Book[] = [
  {
    title: "Los secretos que jamás te contaron",
    author: "Albert Espinosa",
    description: "",
    image: "los-secretos-que-jamas-te-contaron.jpg",
    link: "https://amzn.to/4kjexmA",
    category: "growth",
    readAt: { month: 6, year: 2025 },
  },
  {
    title: "The art of deception",
    author: "Kevin Mitnick",
    description: "",
    image: "the-art-of-deception.jpg",
    link: "https://amzn.to/4lu5lg8",
    category: "growth",
    readAt: { month: 5, year: 2024 },
  },
  {
    title: "Rompe la barrera del no",
    author: "Chris Voss",
    description: "",
    image: "rompe-la-barrera-del-no.jpg",
    link: "https://amzn.to/4kmiOWr",
    category: "growth",
    readAt: { month: 2, year: 2024 },
  },
  {
    title: "Habitos atomicos",
    author: "James Clear",
    description: "",
    image: "habitos-atomicos.jpg",
    link: "https://amzn.to/3IcK6Ba",
    category: "growth",
    readAt: { month: 7, year: 2022 },
  },
  {
    title: "Radical focus",
    author: "Christina Wodtke",
    description: "",
    image: "radical-focus.jpg",
    link: "https://amzn.to/3G8z1a2",
    category: "growth",
    readAt: { month: 4, year: 2021 },
  },
  {
    title: "El manual del manager",
    author: "",
    description: "",
    image: "manual-del-manager.png",
    category: "growth",
    readAt: { month: 3, year: 2022 },
  },
  {
    title: "Bill Gates, una biografía no autorizada",
    author: "Riccardo Staglianò",
    description: "",
    image: "bill-gates-una-biografia-no-autorizada.jpg",
    link: "https://amzn.to/3Tp0Mb3",
    category: "growth",
    readAt: { year: 2007 },
  },
];

const softwareBooks: Book[] = [
  // Ordenados del más reciente al más antiguo
  // Libros sin fecha de lectura
  {
    title: "Eloquent JavaScript",
    author: "Marijn Haverbeke",
    description: "",
    image: "eloquent-javascript.jpg",
    link: "https://eloquentjavascript.net/",
    category: "software",
  },
  {
    title: "Don't make me think",
    author: "Steve Krug",
    description: "",
    image: "dont-make-me-think.jpg",
    link: "https://amzn.to/4lu6S5K",
    category: "software",
    readAt: { year: 2011 },
  },
  {
    title: "Learning Patterns",
    author: ["Lydia Hallie", "Addy Osmani"],
    description: "",
    image: "patterns.webp",
    link: "https://www.patterns.dev",
    category: "software",
    readAt: { year: 2023 },
  },
  {
    title: "You don't know JS",
    author: "Kyle Simpson",
    description: "",
    image: "you-dont-know-js.jpg",
    link: "https://github.com/getify/You-Dont-Know-JS/blob/1st-ed/README.md",
    category: "software",
    readAt: { year: 2017 },
  },
  {
    title: "JavaScript: The good parts",
    author: "Douglas Crockford",
    description: "",
    image: "javascript-the-good-parts.jpg",
    link: "https://amzn.to/4ewwMUl",
    category: "software",
    readAt: { year: 2014 },
  },
  {
    title: "Aprendiendo JavaScript",
    author: "Carlos Azaustre",
    description: "",
    image: "aprendiendo-javascript.jpg",
    link: "https://amzn.to/3GvViZ3",
    category: "software",
    readAt: { year: 2023 },
  },
  {
    title: "HTML & CSS: The Good Parts",
    author: "Ben Henick",
    description: "",
    image: "html-css-the-good-parts.jpg",
    link: "https://amzn.to/402dDUd",
    category: "software",
    readAt: { month: 11, year: 2012 },
  },
  {
    title: "Frontend Testing",
    author: "Iago Lastra",
    description: "",
    image: "frontend-testing.png",
    link: "https://amzn.to/3TheaxU",
    category: "software",
    readAt: { month: 3, year: 2022 },
  },
  {
    title: "Desarrollo web con PHP y MySQL",
    author: ["Luke Welling", "Laura Thomson"],
    description: "",
    image: "desarrollo-web-con-php-y-mysql.jpg",
    link: "https://amzn.to/4laSu2F",
    category: "software",
    readAt: { year: 2012 },
  },
  {
    title: "Hackers 4",
    author: ["Stuart McClure", "Joel Scambray", "George Kurtz"],
    description: "",
    image: "hackers-4.jpg",
    link: "https://www.casadellibro.com/libro-ibd-hackers-4-con-cd-rom/9788448139797/922038?srsltid=AfmBOopvpZn4fSUvP-iDp2EU_u_wcZesqzYxzAJmZ5lpDTGMVRbu7N7Y",
    category: "software",
    readAt: { year: 2009 },
  },
  {
    title: "Windows XP Los mejores trucos",
    author: "Preston Gralla",
    description: "",
    image: "windows-xp-los-mejores-trucos.jpg",
    link: "",
    category: "software",
    readAt: { year: 2005 },
  },
];

const bookList: Book[] = [...literatureBooks, ...growthBooks, ...softwareBooks];

export { bookList, literatureBooks, growthBooks, softwareBooks };
