const bookList = [
  {
    title: "El nombre del viento",
    author: "Patrick Rothfuss",
    description: "",
    image: "../src/assets/books/el-nombre-del-viento.jpg",
    link: "https://amzn.to/4lDjZlj",
    category: "reading",
    readAt: "2024-06",
  },
  {
    title: "El temor de un hombre sabio",
    author: "Patrick Rothfuss",
    description: "https://amzn.to/3G8Affb",
    image: "../src/assets/books/el-temor-de-un-hombre-sabio.jpg",
    link: "",
    category: "reading",
    readAt: "2025-07",
  },
  {
    title: "El manual del manager",
    author: "",
    description: "",
    image: "../src/assets/books/manual-del-manager.png",
    link: "",
    category: "growth",
    readAt: "2022-03",
  },
  {
    title: "La fortaleza digital",
    author: "Dan Brown",
    description: "",
    image: "../src/assets/books/la-fortaleza-digital.jpg",
    link: "https://amzn.to/3I80keZ",
    category: "reading",
    readAt: "2024-08",
  },
  {
    title: "La conspiración",
    author: "Dan Brown",
    description: "",
    image: "../src/assets/books/la-conspiracion.jpg",
    link: "https://amzn.to/3GwLX38",
    category: "reading",
    readAt: "2012-01",
  },
  {
    title: "Blackwater - La riada",
    author: "Michael McDowell",
    description: "",
    image: "../src/assets/books/blackwater-la-riada.jpg",
    link: "https://amzn.to/4khS7lG",
    category: "reading",
    readAt: "2024-01",
  },
  {
    title: "Rompe la barrera del no",
    author: "Chris Voss",
    description: "",
    image: "../src/assets/books/rompe-la-barrera-del-no.jpg",
    link: "https://amzn.to/4kmiOWr",
    category: "growth",
    readAt: "2024-02",
  },
  {
    title: "HTML & CSS: The Good Parts",
    author: "Ben Henick",
    description: "",
    image: "../src/assets/books/html-css-the-good-parts.jpg",
    link: "https://amzn.to/402dDUd",
    category: "software",
    readAt: "2017-11",
  },
  {
    title: "Cicatriz",
    author: "Juan Gómez-Jurado",
    description: "",
    image: "../src/assets/books/cicatriz.jpg",
    link: "https://amzn.to/4nqXO3H",
    category: "reading",
    readAt: "2022-09",
  },
  {
    title: "El paciente",
    author: "Juan Gómez-Jurado",
    description: "",
    image: "../../src/assets/books/el-paciente.jpg",
    link: "https://amzn.to/4ezDyc7",
    category: "reading",
    readAt: "2022-08",
  },
  {
    title: "Reina Roja",
    author: "Juan Gómez-Jurado",
    description: "",
    image: "../src/assets/books/reina-roja.jpg",
    link: "https://amzn.to/4lGKPct",
    category: "reading",
    readAt: "2022-10",
  },
  {
    title: "Loba Negra",
    author: "Juan Gómez-Jurado",
    description: "",
    image: "../src/assets/books/loba-negra.jpg",
    link: "https://amzn.to/44sHKWp",
    category: "reading",
    readAt: "2023-01",
  },
  {
    title: "La historia secreta del señor White",
    author: "Juan Gómez-Jurado",
    description: "",
    image: "../src/assets/books/la-historia-secreta-del-senor-white.jpg",
    link: "https://amzn.to/40CrPn5",
    category: "reading",
    readAt: "2022-12",
  },
  {
    title: "Frontend Testing",
    author: "Iago Lastra Rodríguez",
    description: "",
    image: "../../src/assets/books/frontend-testing.png",
    link: "https://amzn.to/3TheaxU",
    category: "software",
  },
  {
    title: "Eloquent JavaScript",
    author: "Marijn Haverbeke",
    description: "",
    image: "../../src/assets/books/eloquent-javascript.jpg",
    link: "https://eloquentjavascript.net/",
    category: "software",
  },
  {
    title: "The art of deception",
    author: "Kevin Mitnick",
    description: "",
    image: "../../src/assets/books/the-art-of-deception.jpg",
    link: "https://amzn.to/4lu5lg8",
    category: "growth",
    readAt: "2024-05",
  },
  {
    title: "Un lugar llamado libertad",
    author: "Ken Follett",
    description: "",
    image: "../src/assets/books/un-lugar-llamado-libertad.jpg",
    link: "https://amzn.to/3ZYGHft",
    category: "reading",
    readAt: "2010-10",
  },
  {
    title: "Los pilares de la tierra",
    author: "Ken Follett",
    description: "",
    image: "../src/assets/books/los-pilares-de-la-tierra.jpg",
    link: "https://amzn.to/4lghpSG",
    category: "reading",
    readAt: "2012-03",
  },
  {
    title: "It",
    author: "Stephen King",
    description: "",
    image: "../src/assets/books/it.jpg",
    link: "https://amzn.to/3Ti6knI",
    category: "reading",
    readAt: "2005-05",
  },
  {
    title: "La cúpula",
    author: "Stephen King",
    description: "",
    image: "/images/books/la-cupula.jpg",
    link: "https://amzn.to/3ZYKtpc",
    category: "reading",
  },
  {
    title: "Cell",
    author: "Stephen King",
    description: "",
    image: "/images/books/cell.jpg",
    link: "https://amzn.to/3TmBzhy",
    category: "reading",
    readAt: "2004-01",
  },
  {
    title: "Blockade Billy",
    author: "Stephen King",
    description: "",
    image: "/images/books/blockade-billy.jpg",
    link: "https://amzn.to/4lB5iiA",
    category: "reading",
    readAt: "2005-06",
  },
  {
    title: "La historia de lisey",
    author: "Stephen King",
    description: "",
    image: "/images/books/historia-de-lisey.jpg",
    link: "https://amzn.to/44KXGED",
    category: "reading",
    readAt: "2008-09",
  },
  {
    title: "Hackers 4",
    author: ["Stuart McClure", "Joel Scambray", "George Kurtz"],
    description: "",
    image: "../../src/assets/books/hackers-4.jpg",
    link: "https://www.casadellibro.com/libro-ibd-hackers-4-con-cd-rom/9788448139797/922038?srsltid=AfmBOopvpZn4fSUvP-iDp2EU_u_wcZesqzYxzAJmZ5lpDTGMVRbu7N7Y",
    category: "software",
    readAt: "2009",
  },
  {
    title: "Desarrollo web con PHP y MySQL",
    author: ["Luke Welling", "Laura Thomson"],
    description: "",
    image: "../../src/assets/books/desarrollo-web-con-php-y-mysql.jpg",
    link: "https://amzn.to/4laSu2F",
    category: "software",
  },
  {
    title: "Windows XP Los mejores trucos",
    author: "Preston Gralla",
    description: "",
    image: "../src/assets/books/windows-xp-los-mejores-trucos.jpg",
    link: "",
    category: "software",
  },
  {
    title: "Bill Gates, una biografía no autorizada",
    author: "",
    description: "",
    image: "../src/assets/books/bill-gates-una-biografia-no-autorizada.jpg",
    link: "https://amzn.to/3Tp0Mb3",
    category: "growth",
  },
  {
    title: "Don't make me think",
    author: "Steve Krug",
    description: "",
    image: "../src/assets/books/dont-make-me-think.jpg",
    link: "https://amzn.to/4lu6S5K",
    category: "software",
  },
  {
    title: "JavaScript: The good parts",
    author: "Douglas Crockford",
    description: "",
    image: "../src/assets/books/javascript-the-good-parts.jpg",
    link: "https://amzn.to/4ewwMUl",
    category: "software",
  },
  {
    title: "You don't know JS",
    author: "Kyle Simpson",
    description: "",
    image: "../src/assets/books/you-dont-know-js.jpg",
    link: "https://github.com/getify/You-Dont-Know-JS/blob/1st-ed/README.md",
    category: "software",
  },
  {
    title: "Aprendiendo JavaScript",
    author: "Carlos Azaustre",
    description: "",
    image: "../src/assets/books/aprendiendo-javascript.jpg",
    link: "https://amzn.to/3GvViZ3",
    category: "software",
  },
  {
    title: "El señor de los anillos (Trilogía)",
    author: "J.R.R. Tolkien",
    description: "",
    image: "/images/books/el-señor-de-los-anillos.jpg",
    link: "https://amzn.to/4knjcEe",
    category: "reading",
  },
  {
    title: "El Hobbit",
    author: "J.R.R. Tolkien",
    description: "",
    image: "/images/books/el-hobbit.jpg",
    link: "https://amzn.to/3ZYTPkO",
    category: "reading",
    readAt: "2006-01",
  },
  {
    title: "El médico",
    author: "Noah Gordon",
    description: "",
    image: "/images/books/el-medico.jpg",
    link: "https://amzn.to/4kqWXx9",
    category: "reading",
    readAt: "2004-06",
  },
  {
    title: "Chaman",
    author: "Noah Gordon",
    description: "",
    image: "/images/books/chaman.jpg",
    link: "https://amzn.to/4lGo8VL",
    category: "reading",
  },
  {
    title: "Habitos atomicos",
    author: "James Clear",
    description: "",
    image: "../src/assets/books/habitos-atomicos.jpg",
    link: "https://amzn.to/3IcK6Ba",
    category: "growth",
    readAt: "2022-07",
  },
  {
    title: "Falcó",
    author: "Arturo Perez Reverte",
    description: "",
    image: "/images/books/falco.jpg",
    link: "https://amzn.to/45TbFt5",
    category: "reading",
    readAt: "2020-06",
  },
  {
    title: "Corazones en la Atlántida",
    author: "Stephen King",
    description: "",
    image: "/images/books/corazones-en-la-atlantida.jpg",
    link: "https://www.casadellibro.com/libro-corazones-en-la-atlantida/9788497592956/873686",
    category: "reading",
    readAt: "2003-06",
  },
  {
    title: "Los secretos que jamás te contaron",
    author: "Albert Espinosa",
    description: "",
    image: "../src/assets/books/los-secretos-que-jamas-te-contaron.jpg",
    link: "https://amzn.to/4kjexmA",
    category: "growth",
    readAt: "2025-06",
  },
  {
    title: "El último trabajo del señor Luna",
    author: "César Mallorquí",
    description: "",
    image: "/images/books/el-ultimo-trabajo-del-senor-luna.jpg",
    link: "https://amzn.to/3IgJWZy",
    category: "reading",
    readAt: "2003-02",
  },
];

export { bookList };
