name: Node.js Build & Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: |
          git config user.name baumannzone
          git config user.email jorge.baumann.aguilar@gmail.com
          git add ./dist
          git commit -m "[Bot] Push dist folder to deploy :v:"
          git push origin build-deploy
    
